services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: geo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - postgis_data:/var/lib/postgresql/data
volumes:
  postgis_data:   
